version: "4.28"
services: 
    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        environment: 
            - PGADMIN_DEFAULT_EMAIL=joaopfq@alu.ufc.br
            - PGADMIN_DEFAULT_PASSWORD=12345
        ports: 
            - "89:80"
        networks: 
            - postgres-network      
    postgres:
        image: postgres:bullseye
        container_name: postgres_container
        environment: 
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5432:5432"
        networks: 
            - postgres-network                
networks: 
    postgres-network:
        driver: bridge